# Generated by Django 4.1.1 on 2022-09-08 09:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options_alter_blog_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
